name: TrueNAS SCALE Developer Build
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: Clean
      run: sudo rm -rf $GITHUB_WORKSPACE/*
      
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Check
      run: sudo make check
         
    - name: Git Checkout
      run: sudo make checkout
      
    - name: Build Packages
      run: sudo make packages

    - name: Build Update File
      run: sudo make update

    - name: Build ISO
      run: sudo make iso 
    
    - name: Stage Artifacts
      if: success()
      run: |
           sudo rm -rf artifacts || true
           sudo mkdir -p artifacts/packages
           sudo mv tmp/release artifacts/release
           sudo mv logs artifacts/logs
           sudo mv tmp/pkgdir artifacts/packages

    - name: Stage Failure Logs
      if: failure()
      run: |
           sudo rm -rf artifacts || true
           sudo mkdir -p artifacts/packages
           sudo mv logs artifacts/logs
   
    - name: Upload Artifacts
      if: always()
      uses: koraykoska/s3-upload-github-action@master
      env:
        FILE: ./artifacts/
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        S3_BUCKET: 'truenas-github'
        S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}

             
  cleanup:
    if: always()
    needs: [build]
    runs-on: self-hosted
    steps:
    - name: Run clean
      run: sudo make clean
